# Site settings
title: 看看你极限深蓝的 Blog
email: 624486877@qq.com
description: 看看你极限深蓝的 Blog
baseurl: ""
url: https://lzc6244.github.io/
author: 看看你极限深蓝

# Theme
theme: minima

# Minima skin (auto/classic/dark)
minima:
  skin: auto
  date_format: "%Y-%m-%d"

# Header pages
# 首页已通过 site-title 链接，无需重复添加

# Social links
github_username: LZC6244
zhihu_username: mai-da-3

# avatar
avatar: /imgs/gravatar.jpg
favicon: /favicons/favicon.ico

# disqus config
disqus:
  shortname: https-lzc6244-github-io

# Google Analytics
google_analytics: UA-154779982-1

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
